### ISSUE TITLE
Respect  Authorship

### ISSUE THREAD

**Issue by genesixx** [Suicide-Squirrel/android_device_lge_g4-common#1]

**Comment by steadfasterX** [comment]
I added a topic in https://github.com/Suicide-Squirrel/android_device_lge_g4-common and all related repos (even when you see there that they are forked).

hope thats what you wanted. Besides this all contributors can be found in the commits or the stats pages of github

**Comment by genesixx** [comment]
i dont see any contributors at all here https://github.com/Suicide-Squirrel/android_device_lge_g4-common/commit/7153224576c1efbe65770110dd2da9eb84a60b16

**Comment by steadfasterX** [comment]
thats why i added this:

![screenshot_003](https://user-images.githubusercontent.com/8750713/33137889-660626e2-cfa9-11e7-95c6-9e31cd6fc16d.png)

**Comment by genesixx** [comment]
and ? that's not enough. You can't commit and say "yeah it's the work of Jim paul and the fucking intern" no

**Comment by steadfasterX** [comment]
Fucking.. ?! 
I see.
